<div>
    <div class="page-title">
        <h1><?php echo $this->__('Email for Twitter login confirmation') ?></h1>
    </div>
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="twitter-email-confirm-form">
        <div class="content">
            <ul class="form-list">
                <li>
                    <label for="email" class="required"><em>*</em><?php echo $this->__('Email') ?></label>
                    <div class="input-box">
                        <input type="text" name="email" class="input-text required-entry validate-email" id="email" title="<?php echo $this->__('Email') ?>" />
                    </div>
                    <div class="">
                        <button type="submit" class="button" title="<?php echo $this->__('Submit') ?>" name="send" id="send2">
                            <span><span><?php echo $this->__('Submit') ?></span></span>
                        </button>
                    </div>
                </li>
            </ul>
        </div>
    </form>
    <script type="text/javascript">
        //<![CDATA[
        var dataForm = new VarienForm('twitter-email-confirm-form', true);
        //]]>
    </script>
</div>